version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "docker-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ikyeet87s7dm"
s3_prefix = "docker-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "NginxRepo=\"OrderedDict([('Fn::ImportValue', 'NginxRepository')])\" FlaskRepo=\"OrderedDict([('Fn::ImportValue', 'FlaskRepository')])\""
